# Generated by Django 3.2 on 2023-03-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=25)),
                ('from_mail', models.EmailField(max_length=50)),
                ('subject', models.TextField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(max_length=50000)),
            ],
        ),
    ]
