# Generated by Django 4.1.3 on 2023-03-02 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField(default=0.0, verbose_name='marks obtained')),
                ('max_marks', models.IntegerField(default=0.0, verbose_name='max marks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.student_data')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.subject')),
            ],
        ),
    ]
