# Generated by Django 3.2 on 2023-03-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marklist',
            name='term',
            field=models.CharField(default='', max_length=10),
        ),
    ]
